### ISSUE TITLE
Rofi prompt appears but none of the functions works

### ISSUE THREAD

**Issue by Arsezar** [carvalhudo/usb-dmenu#3]
Good evening. 
I have tried to use this script for my debian 12 and bspwm setup, but unfortunately had one problem with that. When I plugged in an USB flash drive the script ran correctly and asked me to choose an option, but after choosing "mount" there are no notifications about successful mount and there is no actual mounting. Maybe something is not working because of permissions necessity for mkdir, rmdir, etc., or due to some variables inside the script which I do not have in .zshrc. Do I need to specify the "GROUP" parameter in udev rules for this script? Did I miss something significant about configuration? Thank you in advance.

**Comment by andrelcmoreira** [comment]
Hi, @Arsezar. Thanks for let me know about this issue. No, you don't need to set any environment variable nor provide an external configuration to script. Once you have all dependencies in place, the installation steps described on README file should be suficient to script do its work. Please notice that I tested the script only on my machine (running void linux), but in theory it should work on other linux distributions as well.

I will take some time to setup a debian virtual machine to try to debug the script and figure out what is happening, but I let you know about my tests and conclusions.

**Comment by Arsezar** [comment]
Good morning, @carvalhudo. Thank you for your feedback. I will also try the script again and maybe I will find a solution for this issue.

**Comment by andrelcmoreira** [comment]
Hi, I reproduced your scenario on a virtual machine and I figured out the problem. I forgot usb-rofi was strictly tied to runit daemon init and debian is systemd based. The fix is available on **fix_mounting_systemd** branch, could you checkout it and test again?
